### ISSUE TITLE
v0.44.1 tag is not present anymore in gcr.io/cadvisor/cadvisor

### ISSUE THREAD

**Issue by dirtyValera** [ckotzbauer/helm-charts#105]
`v0.44.1` is renamed to `v0.44.1-test` [link](https://console.cloud.google.com/gcr/images/cadvisor/GLOBAL/cadvisor) . Current chart will be stuck forever with `ErrImagePull`. Use latest tag perhaps?

**Comment by ckotzbauer** [comment]
Released the chart-release 2.2.1 with 0.44.0 as default.
