### ISSUE TITLE
Unable to set namespace on some of the templates with kustomize

### ISSUE THREAD

**Issue by RnkeZ** [ckotzbauer/helm-charts#128]
Most of the templates in the chart are missing following key:
`namespace: {{ .Release.Namespace}}`.

**Comment by ckotzbauer** [comment]
Helm sets them automatically, there's no need for a placeholder in most of the cases.

**Comment by RnkeZ** [comment]
We are using kustomized helm and in that setup, the namespace is not propagated to resources if they don't contain _.Release.Namespace_ key

**Comment by ckotzbauer** [comment]
Okay, that's a necessary info to understand this issue correctly :wink:.
Feel free to open a PR for the charts/templates which have to updated.

**Comment by RnkeZ** [comment]
Sorry I was in a rush so I failed to deliver a proper description. Okay, I will provide a PR for this issue :+1:
