### ISSUE TITLE
feat: Make configmap permission in c-role of sbom-operator chart optional

### ISSUE THREAD

**Issue by hardwarefresser** [ckotzbauer/helm-charts#200]
Hi,
### Current state
the k8s [clusterRole](https://github.com/ckotzbauer/helm-charts/blob/main/charts/sbom-operator/templates/clusterrole.yaml#L21) assigned to the sbom-operator service account includes permissions to `create` `get` `delete` `list` configMaps at the cluster scope. I know that this is needed in case the operator stores the SBOMs as configMaps ([target: configmap](https://github.com/ckotzbauer/sbom-operator?tab=readme-ov-file#configmap)).

### Issue
The above mentioned permissions are included in the c-role regardless of whether the target includes configmap or not. If the sbom-operator is configured to just push SBOMs to Git or Dependencytrack, the service does not need those permissions.

### Potential solution
My Idea is to wrap something like `{{- if contains "configmap" .Values.args.targets }}` around the  [configmap permissions](https://github.com/ckotzbauer/helm-charts/blob/main/charts/sbom-operator/templates/clusterrole.yaml#L21) in the template, so that they are only included when really needed.

Just wanted to confirm that my idea is valid and I did not miss anything. If you think that it makes sense, let me know and I can provide a PR!

**Comment by hardwarefresser** [comment]
Meanwhile, I implemented it in a [fork here](https://github.com/hardwarefresser/helm-charts/commit/a8b0a64e56df3453090b7c8001ee79717acbf0e7). And indeed, it seems to work as intended. In case you want to check it out.

Like I said, I can open a PR in case you confirm that I considered everything.

**Comment by ckotzbauer** [comment]
Hi @hardwarefresser,
thanks for this idea, this would be a great addition to reduce permissions for most of the installations. I'm just not sure if there might be an additional null-check needed in the template to handle null "args" or "targets" properly, so we do not break anything.
I would be great if you could open a PR for that, I really appreciate that, thanks!

**Comment by hardwarefresser** [comment]
Thanks for getting back!
Will check out if a null-check is needed and open the PR then
