### ISSUE TITLE
update nfs-client-provisioner to include accessModes

### ISSUE THREAD

**Issue by si458** [ckotzbauer/helm-charts#37]
the original helm chart will be going soon, so im hoping to use this as a base for the nfs-client helm chart

could you maybe ask them to take over that chart for the nfs-client anyways?

can you update your chart to include the accessmode that they have included in there chart?

https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner
https://github.com/helm/charts/commit/a4a35c39cb15c82637cd1762d5d989b3cebe1769#diff-ec531825a9cf4a43add171082b59e73dff020a2e22bc911fb2b8f66005370226

**Comment by ckotzbauer** [comment]
> could you maybe ask them to take over that chart for the nfs-client anyways?

What do you mean exactly?

> can you update your chart to include the accessmode that they have included in there chart?

Feel free to open a PR against this repo to add the option.

/kind feature
/label help wanted

**Comment by si458** [comment]
#38 should update it for you :)

**Comment by ckotzbauer** [comment]
thanks for your PR @si458! :+1:
