### ISSUE TITLE
Could not configure a source for OOM detection

### ISSUE THREAD

**Issue by dmitrii-didenko** [ckotzbauer/helm-charts#71]
Hi!

Thanks for the project.

I've tried installing cadvisor and found an issue with oom metrics being not available due to permission issue:
```
❯ kl cadvisor-ktblb
W0910 14:59:26.756250       1 machine_libipmctl.go:62] There are no NVM devices!
W0910 14:59:26.805682       1 manager.go:289] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: operation not permitted
```

It can be fixed by adding the following settings to the daemonset:
```
        securityContext:
          privileged: true
```
Do you have plans to add this to the chart? Or there is another option to enable oom detection?

**Comment by ckotzbauer** [comment]
Feel free to open a PR to add securityContext-support. Would be a valuable change.

**Comment by dmitrii-didenko** [comment]
Hi! Added PR here https://github.com/ckotzbauer/helm-charts/pull/72
Could you review it, please?
